In [1]:
import numpy as np

In [6]:
"""
random numbers generation
random.randint(start, stop, size=n



"""
#Generates random age data for 500 people between 18 and 65
age = np.random.randint(18,66, size=500)
print(age)

#random height for data for 500 people between 4'6 and 7'0 height_inches = np.random.randint(54,84, size=500)
height_inches = np.random.randint(54, 84, size=500)
print(height_inches)

#height in feet
height_feet = height_inches/12.0

#random weights data for 500 people between 100 and 300lbs
weight = np.random.randint(100,300,size=500)

#calculate bmi using the formular: weight(kg)/height(m)^2
height_meters = height_inches * 0.0254
weight_kg = weight * 0.453592
bmi = weight_kg/(height_meters**2)
print(bmi)


[34 60 21 34 36 27 60 32 37 64 57 65 52 48 65 48 46 60 61 54 28 48 30 53
 55 52 24 24 43 53 61 59 43 57 65 40 56 25 61 58 60 55 31 39 34 51 24 31
 48 21 50 53 46 35 31 28 54 34 48 21 49 31 52 23 20 65 40 26 53 23 37 48
 31 18 41 57 53 57 54 22 44 26 53 46 49 44 26 23 39 42 56 62 25 52 48 27
 18 45 56 31 19 53 45 33 34 62 53 38 43 32 34 46 19 32 26 27 30 58 31 57
 38 57 52 23 49 28 43 52 37 35 57 23 30 56 33 40 65 19 49 40 61 62 20 37
 18 22 19 23 48 40 29 65 34 57 26 33 29 60 18 29 24 39 62 52 33 35 58 50
 48 30 41 53 33 40 37 56 32 54 18 42 64 38 39 48 28 48 30 31 21 47 59 44
 57 64 37 55 50 40 32 20 38 36 64 19 25 61 53 36 22 25 27 35 20 32 38 45
 49 57 27 45 20 25 47 58 34 61 27 18 60 31 24 28 26 30 64 23 58 23 38 54
 51 31 44 52 62 19 46 53 40 26 29 54 41 62 34 19 65 20 36 31 26 40 21 60
 47 55 45 23 21 63 57 20 44 53 27 26 37 57 52 56 44 28 21 32 56 35 61 36
 45 29 39 20 34 51 55 53 26 27 31 22 19 21 30 35 52 59 63 38 51 63 38 65
 21 36 39 58 50 44 53 49 22 21 53 42 58 45 35 35 42

In [11]:
#creating array items with array()functions
x = np.array(range(10), dtype=int)
print(x)

#multidimensional array
multi = np.array([[1,3], [4,5]])
print(multi)

#shape - used to check how many rows and columns are in the array
print(multi.shape)
print(x.shape)


[0 1 2 3 4 5 6 7 8 9]
[[1 3]
 [4 5]]
(2, 2)
(10,)


In [13]:
#numpy arrays can have field names
a = np.zeros((2,2), dtype=[("x", "f4")])
print(a)

[[(0.,) (0.,)]
 [(0.,) (0.,)]]


In [14]:
"""
numpy attributes
.ndim - gives the number of axes or dimensions in the array
.shapes - gives dimensions of the arrays, eg, total rows and columns
.size - gives the total number of elements of the array.
.itemsize - gives the size of each element of the array in bytes
.data - used in cases where you want to access the elements in an array using indexes.
"""
array_attribute = np.array([[10,20,30],[14,12,16]])

#ndim - number of dimensions
print(array_attribute.ndim) # teo dimensions array

#shape - total rows and columns
print(array_attribute.shape) #here we have 2 rows and 3 columns.

#size -total number of element of the array
print(array_attribute.size)

#dtype - datatype of items in the array
print(array_attribute.dtype)

#itemsize - size of each element of the array in bytes
print(array_attribute.itemsize)


2
(2, 3)
6
int64
8


In [5]:

"""
numpy creation with initial placeholder content
np.zeros() - creates an array of zeros
np.ones()-creates an array of ones
np.empty()- creates an empty array
np.full()- creates a full array
np.eye() - creates an identity matrix
np.arange()- arange(start, stop, step) -creates an array between start and stop, with a sequence of step
np. linspace()- returns evenly spaced numbers over a specified interval, start, stop, num(samples to generate), dtype(datatype)

"""
import numpy as np
#creates an array of zeros
a = np.zeros((2,3))
print("array of zeros",a)

#creates an array of ones
b = np.ones((3,4))
print(b)

#create an empty array
c = np.empty((2,3))
print("empty array",c)

#create a full array
d = np.full((3,4),10)
print("array with equal values in all dimensions that is 10",d)

#create an identity matrix
e = np.eye(2,2)
print(2)

#create random values in array, two columns and rows
f = np.random.random((2,2))
print("two columns and two rows\n",f)

#arange()
print(np.arange(10,100,5))

#linspace()- indicates how many elements you need in an array
print(np.linspace(0,2,9))


array of zeros [[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
empty array [[0. 0. 0.]
 [0. 0. 0.]]
array with equal values in all dimensions that is 10 [[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]
2
two columns and two rows
 [[0.33991245 0.71663255]
 [0.80233757 0.55543512]]
[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [7]:
"""
integer indexing,array indexing,boolean array indexing,slicing and altering.


"""
import numpy as np
#displays value from 10 to 100 stepping with 20
a = np.arange(10,100,20)
print(a)

#accessing the values in array using the index position
print("item index at position 3 is",a[3])

#accessing values from 2:4 slicing
print(a[2:4])

c = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(c)

#access item in second row, third column
print(c[1,3],c[2,2])





[10 30 50 70 90]
item index at position 3 is 70
[50 70]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8 11


In [10]:
"""
Basic arithmetic operations on numpy


"""
import numpy as np

#arrays of 4 values, created with []
a = np.array([20,30,40,40])
print(a)

#we can arange() to create an array
b = np.arange(4) 
print(b)

# add the two arrays together
total = a + b
print(total)

#use the add ()function
t2 = np.add(a,b)
print(t2)

# use the divide() function
div = np.divide(b,a)
print(div)

#use the multiply() function
mult = np.multiply(a,b)
print(mult)

#use the subtract()function
sub = np.subtract(a,b)
print(sub)

#you can use exponent**
exp = a**2
print(exp)


[20 30 40 40]
[0 1 2 3]
[20 31 42 43]
[20 31 42 43]
[0.         0.03333333 0.05       0.075     ]
[  0  30  80 120]
[20 29 38 37]
[ 400  900 1600 1600]


In [12]:
"""
Mathematical functions in numpy 
Examples: sin(), cos(),tan()floor(),ceil(),sqrt(), maximum(),minimum(),sum(),

"""
import numpy as np
a = np.array([20,30,40,50])

#sin()
print(np.sin(a))

#cos()
print(np.cos(a))

#tan()
print(np.tan(a))

#floor()
print(np.floor(a))

#ceil()
print(np.ceil(a))

#sqrt()
print(np.sqrt(a))

#the maximum() function compares two arrays and returns a new array containing element-wise
#maximum of array elements
print(np.maximum([2,3,4],[1,5,2]))

#the minimum() function compares two arrays and return a new array containing element-wise
#minimum  of array elements
print(np.minimum([2,3,4],[1,5,2]))

#sum() function returns the sum array element over a given axis.
print(np.sum([[2,4,],[1,6]],axis=0))




[ 0.91294525 -0.98803162  0.74511316 -0.26237485]
[ 0.40808206  0.15425145 -0.66693806  0.96496603]
[ 2.23716094 -6.4053312  -1.11721493 -0.27190061]
[20 30 40 50]
[20 30 40 50]
[4.47213595 5.47722558 6.32455532 7.07106781]
[2 5 4]
[1 3 2]
[ 3 10]


In [15]:
"""
changing the shape of the array
-An array has a shape given by the number of the element along each axis
-The shape of an array can be changed with ravel() and reshape()function
-Both ravel() and reshape() return a modified array but do not change the original array
-The function ravel() returns a flattened array, such as one dimensional array, containing the elements
-The function reshape() gives a new shape to an array without changing its data.

"""

import numpy as np

a = np.floor(10 * np.random.random((3,4)))
print(a)

[[5. 0. 0. 0.]
 [0. 1. 6. 4.]
 [1. 5. 4. 0.]]
